FROM node:20

# RUN apt-get update && apt-get install -y openssl libssl-dev vim

# WORKDIR /gateway

# COPY ./*.json .

# RUN npm install

# COPY ./src ./src

# # COPY ./prisma ./prisma

# COPY ./.env .

# # RUN npx prisma generate

# RUN npm run build

# EXPOSE 4000

# CMD ["npm" , "run" , "start"]
CMD ["tail" , "-f" , "/dev/null"]

